# ============================================
# Spring Boot configuration for "dev" profile.
# ============================================

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true

application:
  elasticsearch:
    path: '192.168.99.100:9200'
